<div class="h-full">

    <iframe class="w-full" height=400 src="https://www.youtube.com/embed/X_qo3lnRS1k" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

    <iframe class="w-full mt-10" height=400 src="https://www.youtube.com/embed/mhDJNfV7hjk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

    <iframe class="w-full mt-10" height=400 src="https://www.youtube.com/embed/fcD94e93cCk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


    <blockquote class="tiktok-embed" cite="https://www.tiktok.com/@beckhamsplate/video/7014163396144745733" data-video-id="7014163396144745733" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@beckhamsplate" href="https://www.tiktok.com/@beckhamsplate">@beckhamsplate</a> Reply to @dufauteutsjgxmgx sorry, had to do it one more time 🤤 <a title="salmonbowl" target="_blank" href="https://www.tiktok.com/tag/salmonbowl">#salmonbowl</a> <a title="salmonrice" target="_blank" href="https://www.tiktok.com/tag/salmonrice">#salmonrice</a> <a title="sushibowl" target="_blank" href="https://www.tiktok.com/tag/sushibowl">#sushibowl</a> <a title="salmon" target="_blank" href="https://www.tiktok.com/tag/salmon">#salmon</a> <a title="food" target="_blank" href="https://www.tiktok.com/tag/food">#food</a> <a title="recipe" target="_blank" href="https://www.tiktok.com/tag/recipe">#recipe</a> <a target="_blank" title="♬ original sound - Sienna" href="https://www.tiktok.com/music/original-sound-7014163410963516166">♬ original sound - Sienna</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>

    <blockquote class="tiktok-embed" cite="https://www.tiktok.com/@simplefood4you/video/6960302340813507845" data-video-id="6960302340813507845" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@simplefood4you" href="https://www.tiktok.com/@simplefood4you">@simplefood4you</a> TACO CRUNCH WRAP🌮  <a title="recipe" target="_blank" href="https://www.tiktok.com/tag/recipe">#recipe</a> <a title="cooking" target="_blank" href="https://www.tiktok.com/tag/cooking">#cooking</a> <a title="foodie" target="_blank" href="https://www.tiktok.com/tag/foodie">#foodie</a> <a title="foodtiktok" target="_blank" href="https://www.tiktok.com/tag/foodtiktok">#foodtiktok</a> <a title="food" target="_blank" href="https://www.tiktok.com/tag/food">#food</a> <a title="foryou" target="_blank" href="https://www.tiktok.com/tag/foryou">#foryou</a> <a title="fyp" target="_blank" href="https://www.tiktok.com/tag/fyp">#fyp</a> <a target="_blank" title="♬ All The Way Up - Fat Joe & Remy Ma" href="https://www.tiktok.com/music/All-The-Way-Up-6756162597461952514">♬ All The Way Up - Fat Joe & Remy Ma</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>

    <blockquote class="tiktok-embed" cite="https://www.tiktok.com/@nutrientmatters/video/6951107082888285445" data-video-id="6951107082888285445" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@nutrientmatters" href="https://www.tiktok.com/@nutrientmatters">@nutrientmatters</a> I can eat 10 of these in one sitting and I’m not ashamed just a little bit though <a title="garlicbreadrecipe" target="_blank" href="https://www.tiktok.com/tag/garlicbreadrecipe">#garlicbreadrecipe</a> <a title="iftarrecipe" target="_blank" href="https://www.tiktok.com/tag/iftarrecipe">#iftarrecipe</a> <a target="_blank" title="♬ Chill Vibes - Martin Czerny" href="https://www.tiktok.com/music/Chill-Vibes-6833581337811617794">♬ Chill Vibes - Martin Czerny</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>
</div>
